### ISSUE TITLE
Міст не відновив роботу після невдалого запиту

### ISSUE THREAD

**Issue by vmaksymiv** [openprocurement/openprocurement.tender.competitivedialogue#114]
```
2017-01-06 08:01:12,996 - openprocurement.tender.competitivedialogue.databridge - WARNING - Forward worker died!
2017-01-06 08:01:12,996 - openprocurement.tender.competitivedialogue.databridge - ERROR - {'msg': '', 'status_int': 504, 'response': <restkit.wrappers.Response object at 0x7f08400d1c10>}
Traceback (most recent call last):
  File "/home/comp.dialogue/openprocurement.buildout/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/databridge.py", line 628, in get_competitive_dialogue_forward
    for tender_data in self.get_tenders(params=params, direction="forward"):
  File "/home/comp.dialogue/openprocurement.buildout/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/databridge.py", line 249, in get_tenders
    extra_headers={'X-Client-Request-ID': generate_req_id()})
  File "/home/comp.dialogue/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 559, in sync_tenders
    response = self.get(self.prefix_path, params_dict=params)
  File "/home/comp.dialogue/.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 114, in get
    params_dict=params_dict, **params)
  File "/home/comp.dialogue/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 62, in request
    params_dict=params_dict, **params
  File "/home/comp.dialogue/.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 210, in request
    response=resp)
RequestFailed: {'msg': '', 'status_int': 504, 'response': <restkit.wrappers.Response object at 0x7f08400d1c10>}
```

**Comment by Krokop** [comment]
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/118

**Comment by vmaksymiv** [comment]
Після оновлення проблема все ще присутня:
```
2017-01-27T18:44:19.721Z 	Restarting synchronization
2017-01-27T18:44:04.464Z 	Error response 
2017-01-27T18:44:04.463Z 	Backward worker died!
2017-01-27T18:43:34.721Z 	Start forward data sync worker...
2017-01-27T18:43:34.721Z 	Restarting synchronization
2017-01-27T18:43:34.721Z 	Forward worker died!
2017-01-27T18:43:34.721Z 	Start backward data sync worker...
2017-01-27T18:43:34.721Z 	Error response 
2017-01-27T18:43:34.721Z 	Restore forward sync
2017-01-27T18:43:32.458Z 	Backward worker died!
2017-01-27T18:43:32.458Z 	Error response 
2017-01-27T18:43:32.458Z 	Restore backward sync
2017-01-27T18:43:18.471Z 	Sleep forward sync...
```

**Comment by Krokop** [comment]
а є логи в stderr?

**Comment by vmaksymiv** [comment]
Це все, що попало в лог.

Додатково бачимо:
CODE_FILE		/home/comp.dialogue/.buildout/eggs/openprocurement.tender.competitivedialogue-1.0.9-py2.7.egg/openprocurement/tender/competitivedialogue/databridge.py
CODE_FUNC		get_competitive_dialogue_backward
CODE_LINE		636

**Comment by vmaksymiv** [comment]
Треба мати на увазі, що кількість серверів, які обслуговують public точку, весь час міняється.
Коли падає навантаження, то сервер з яким ішла синхронізація, може виключитись. Це основна відмінність production середовища від sandbox.

**Comment by Krokop** [comment]
ПР - https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/123

**Comment by Krokop** [comment]
Зв'язаний issue https://github.com/openprocurement/openprocurement.tender.competitivedialogue/issues/120

**Comment by vmaksymiv** [comment]
Цього буде достатньо щоб побачити проблему?
Викласти код зможем тільки в четвер (якщо буде погодження), і якщо знову не получиться побачити причину, фікс знов відкладеться мінімум на тиждень.

**Comment by Krokop** [comment]
Так, цей варіант або допоможе вирішити проблему, або надасть більш змістовну інформацію.

**Comment by vmaksymiv** [comment]
Потрібно доробити watcher-а для моніторингу роботи моста (наповнення черг, відображення "живих" worker-ів). Це допоможе побачити стус компонент моста у випадку блокування задач.

У всіх "слизьких" місцях, треба поставити "запобіжники", які вбережуть від залипання. Наприклад, одним з варіантів чому міст не може відновити роботу, може бути блокуюючий kill (https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/master/openprocurement/tender/competitivedialogue/databridge.py#L705). Вирішення - додати timeout на виклик.

Я за те, щоб позбутись окремого опрацювання ResourceError https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/master/openprocurement/tender/competitivedialogue/databridge.py#L658. Як показала практика, попереднє виправлення (https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/master/openprocurement/tender/competitivedialogue/databridge.py#L660) не допомогло побачити більше ніж залогував би стандартний обробник - https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/master/openprocurement/tender/competitivedialogue/databridge.py#L665 , а навпаки приховало деталі помилки.

**Comment by vmaksymiv** [comment]
**2017-02-03T18:53:26.290Z 	Restarting synchronization**
2017-02-03T18:53:11.779Z 	Error response 
2017-02-03T18:53:11.778Z 	Backward worker died!
2017-02-03T18:52:41.528Z 	Start forward data sync worker...
2017-02-03T18:52:41.528Z 	Start backward data sync worker...
**2017-02-03T18:52:41.527Z 	Restarting synchronization**
2017-02-03T18:52:39.540Z 	Forward worker died!
2017-02-03T18:52:39.540Z 	Error response 
2017-02-03T18:52:39.540Z 	Restore forward sync
2017-02-03T18:52:30.276Z 	Restore backward sync
2017-02-03T18:52:30.276Z 	Error response 
2017-02-03T18:52:30.276Z 	Backward worker died!
2017-02-03T18:52:24.540Z 	Client forward params: {'feed': 'changes', 'offset': 'b99cffc4149cfe1b3f503c301450ba1e', 'mode': '_all_', 'opt_fields': 'status,procurementMethodType'...
2017-02-03T18:52:24.540Z 	Sleep forward sync...
2017-02-03T18:52:24.540Z 	Restore forward sync

**Comment by vmaksymiv** [comment]
Юху!!! Міст успішно пережив ніч і ранок (scale in/scale out на public серверах).
