### ISSUE TITLE
Неправильна поведінка тесту test_1lot_3bid_1del

### ISSUE THREAD

**Issue by yarsanich** [openprocurement/openprocurement.tender.competitivedialogue#119]
Тест створює 3 пропозиції, одну видаляє. По правилах процедури потрібно мінімум 3 пропозиції для початку пре-кваліфікації. В тілі тесту відбувається кваліфікація, а не повинна.

Команда для запуску:
../../bin/nosetests -sx openprocurement/tender/competitivedialogue/tests/stage1/lot.py

Помилка:
```
ERROR: test_1lot_3bid_1del (openprocurement.tender.competitivedialogue.tests.stage1.lot.CompetitiveDialogueEULotProcessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/yarsanich/openprocurement.buildout/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/tests/stage1/lot.py", line 1507, in test_1lot_3bid_1del
    {"data": {"status": "active.pre-qualification.stand-still"}})
  File "/data/yarsanich/openprocurement.buildout/eggs/WebTest-2.0.20-py2.7.egg/webtest/utils.py", line 37, in wrapper
    return self._gen_request(method, url, **kw)
  File "/data/yarsanich/openprocurement.buildout/eggs/WebTest-2.0.20-py2.7.egg/webtest/app.py", line 736, in _gen_request
    expect_errors=expect_errors)
  File "/data/yarsanich/openprocurement.buildout/eggs/WebTest-2.0.20-py2.7.egg/webtest/app.py", line 632, in do_request
    self._check_status(status, res)
  File "/data/yarsanich/openprocurement.buildout/eggs/WebTest-2.0.20-py2.7.egg/webtest/app.py", line 664, in _check_status
    res)
AppError: Bad response: 403 Forbidden (not 200 OK or 3xx redirect for http://localhost/api/2.3/tenders/e60f46edf86640e59a48c47a0d3bc232?acc_token=9199ff4bbb864ca29566c629b5ab13f1)
{"status": "error", "errors": [{"location": "body", "name": "data", "description": "Can't update tender in current (unsuccessful) status"}]}
-------------------- >> begin captured logging << --------------------

....

openprocurement.tender.competitivedialogue.views.stage1.tender: INFO: Updated tender e60f46edf86640e59a48c47a0d3bc232
openprocurement.api: INFO: Error on processing request "[
    {
        "location": "body", 
        "name": "data", 
        "description": "Can't update tender in current (unsuccessful) status"
    }
]"

```

Всі залежні пакети актуальних версій.

**Comment by itvan** [comment]
@vmaksymiv прохання закрити це issue.
