### ISSUE TITLE
412 response при переініціалізації моста

### ISSUE THREAD

**Issue by vmaksymiv** [openprocurement/openprocurement.tender.competitivedialogue#127]
```
Start backward data sync worker...
Start forward data sync worker... 	
Backward worker died! 	
{'msg': '', 'status_int': 412, 'response': <restkit.wrappers.Response object at 0x7f4299afbfd0>} 
Traceback (most recent call last): 
File "/home/comp.dialogue/.buildout/eggs/openprocurement.tender.competitivedialogue-1.0.13-py2.7.egg/openprocurement/tender/competitivedialogue/databridge.py", line 653, in get_competitive_dialogue_backward for tender_data in self.get_tenders(params=params, direction="backward"): 
File "/home/comp.dialogue/.buildout/eggs/openprocurement.tender.competitivedialogue-1.0.13-py2.7.egg/openprocurement/tender/competitivedialogue/databridge.py", line 218, in get_tenders response = self.initialize_sync(params=params, direction=direction) 
File "/home/comp.dialogue/.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 49, in wrapped_f return Retrying(*dargs, **dkw).call(f, *args, **kw) 
File "/home/comp.dialogue/.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 212, in call raise attempt.get() 
File "/home/comp.dialogue/.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 247, in get six.reraise(self.value[0], self.value[1], self.value[2]) 
File "/home/comp.dialogue/.buildout/eggs/retrying-1.3.3-py2.7.egg/retrying.py", line 200, in call attempt = Attempt(fn(*args, **kwargs), attempt_number, False) 
File "/home/comp.dialogue/.buildout/eggs/openprocurement.tender.competitivedialogue-1.0.13-py2.7.egg/openprocurement/tender/competitivedialogue/databridge.py", line 199, in initialize_sync response = self.tenders_sync_client.sync_tenders(params, extra_headers={'X-Client-Request-ID': generate_req_id()}) 
File "/home/comp.dialogue/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 559, in sync_tenders response = self.get(self.prefix_path, params_dict=params)
File "/home/comp.dialogue/.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 114, in get params_dict=params_dict, **params) 
File "/home/comp.dialogue/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 62, in request params_dict=params_dict, **params 
File "/home/comp.dialogue/.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 210, in request response=resp) RequestFailed: {'msg': '', 'status_int': 412, 'response': <restkit.wrappers.Response object at 0x7f4299afbfd0>}
```

**Comment by Krokop** [comment]
Міст відновив роботу?

**Comment by vmaksymiv** [comment]
https://app.asana.com/0/62467524027769/289093187735897

**Comment by vmaksymiv** [comment]
> Міст відновив роботу?

Ні, так і пробує перепідключитись.

**Comment by vmaksymiv** [comment]
При 412 на sync_tenders не оновлює cookie.

**Comment by Krokop** [comment]
Схоже на те, зараз буду виправляти.

**Comment by Krokop** [comment]
Створив ПР https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/128

**Comment by vmaksymiv** [comment]
@Krokop треба підготувати текст з поясненням змін для погодження на викладення на production.

**Comment by Krokop** [comment]
@vmaksymiv текст сюди писати?

**Comment by vmaksymiv** [comment]
Підготуєм задачу в WS. Але, швидше за все, вже завтра.

**Comment by Krokop** [comment]
@vmaksymiv Ще питання https://app.asana.com/0/62467524027769/289093187735897 - сюди потрібен доступ?

**Comment by vmaksymiv** [comment]
> @vmaksymiv Ще питання https://app.asana.com/0/62467524027769/289093187735897 - сюди потрібен доступ?

Ні, це наша система обліку задач. Додав щоб швидше можна було знайти відповідник в asana/worksection.
