### ISSUE TITLE
No module named pytz

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.tender.competitivedialogue#77]
Traceback (most recent call last):
  File "/home/devel/openprocurement.buildout_2.3/bin/competitive_dialogue_data_bridge", line 23, in <module>
    import openprocurement.tender.competitivedialogue.databridge
  File "/home/devel/openprocurement.buildout_2.3/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/databridge.py", line 27, in <module>
    from pytz import timezone
  File "/home/devel/.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named pytz

**Comment by Krokop** [comment]
Дивно в  requirements pytz є https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/master/requirements.txt#L31

**Comment by kroman0** [comment]
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/master/setup.py#L34 - тут нема

**Comment by kroman0** [comment]
Traceback (most recent call last):
  File "/home/devel/openprocurement.buildout_2.3/bin/competitive_dialogue_data_bridge", line 24, in <module>
    import openprocurement.tender.competitivedialogue.databridge
  File "/home/devel/openprocurement.buildout_2.3/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/databridge.py", line 28, in <module>
    from openprocurement.tender.competitivedialogue.models import CD_UA_TYPE, CD_EU_TYPE, STAGE_2_EU_TYPE, STAGE_2_UA_TYPE, STAGE2_STATUS
  File "/home/devel/.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/devel/openprocurement.buildout_2.3/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/models.py", line 3, in <module>
    from schematics.types import StringType, FloatType
  File "/home/devel/.buildout/eggs/gevent-1.1.1-py2.7-linux-x86_64.egg/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named schematics.types

**Comment by Krokop** [comment]
Як ви його встановлююте?

**Comment by kroman0** [comment]
https://github.com/openprocurement/openprocurement.buildout/tree/cd_bridge
