### ISSUE TITLE
Databridge exception: "Can't update tender in current (complete) status"

### ISSUE THREAD

**Issue by vmaksymiv** [openprocurement/openprocurement.tender.competitivedialogue#83]
```
016-10-10 15:29:18,655 - openprocurement.tender.competitivedialogue.databridge - INFO - Unsuccessful path competitive dialogue id=4205c1a87a554e4c85ad251f24808845 with status complete
2016-10-10 15:29:18,656 - openprocurement.tender.competitivedialogue.databridge - INFO - Schedule retry patch for competitive dialogue id=4205c1a87a554e4c85ad251f24808845
2016-10-10 15:29:18,656 - openprocurement.tender.competitivedialogue.databridge - INFO - Patch competitive dialogue id=4205c1a87a554e4c85ad251f24808845 with status complete

Traceback (most recent call last):
  File "/home/devel/openprocurement.buildout_2.3/src/openprocurement.tender.competitivedialogue/openprocurement/tender/competitivedialogue/databridge.py", line 489, in _patch_dialog_status_with_retry
    self.client.patch_tender(data)
  File "/home/devel/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 326, in patch_tender
    getattr(getattr(tender, 'access', ''), 'token', '')}
  File "/home/devel/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 119, in _patch_resource_item
    url, headers=headers, payload=dumps(payload)
  File "/home/devel/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 84, in patch
    headers=headers, params_dict=params_dict, **params)
  File "/home/devel/.buildout/eggs/openprocurement_client-1.0b2-py2.7.egg/openprocurement_client/client.py", line 62, in request
    params_dict=params_dict, **params
  File "/home/devel/.buildout/eggs/restkit-4.2.2-py2.7.egg/restkit/resource.py", line 204, in request
    response=resp)
Unauthorized: {"status": "error", "errors": [{"location": "body", "name": "data", "description": "Can't update tender in current (complete) status"}]}
```

**Comment by Krokop** [comment]
Таке може трапитись коли одночасно працюють 2 процеси по мосту.

**Comment by vmaksymiv** [comment]
Після перезапуску моста помилка більше не появлялась.

**Comment by Krokop** [comment]
Здається я зрозумів в чому проблема

Міст тримає 2 з'єднання з сервером.
1. tenders_sync_client - для перебору всіх тендорів та витягування тільки тих які потрібно обробити.
2. client - для створення другого етапу та переводу першого в статус `complete`.

Ці 2 точки незалежні одна від одної, тому було спіймано баг коли client перевів перший етап в статус `complete` а tenders_sync_client ще не встиг отриматі данні та знову взяв перший етап в обробку.

Для вирішення питання, потрібно після першої невдалої спроби подивитися на response помилки і далі робити висновки, що роботи першим етапом.
